# Generated by Django 3.2.9 on 2021-11-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('cohort', models.CharField(max_length=50)),
                ('favorite_topic', models.CharField(max_length=100)),
                ('favorite_teacher', models.CharField(max_length=100)),
                ('capstone', models.URLField(max_length=250)),
            ],
        ),
    ]
