# Generated by Django 3.2.8 on 2021-10-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.TextField()),
                ('short', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
