# Generated by Django 3.2.8 on 2021-11-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlitem',
            name='clicks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
