# Generated by Django 3.2.8 on 2021-11-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0002_urlitem_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlitem',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
