# Generated by Django 3.2.8 on 2021-11-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0003_alter_urlitem_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlitem',
            name='comp_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='os',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
