# Generated by Django 3.2.8 on 2021-11-01 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0004_auto_20211101_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlitem',
            name='username',
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('urlitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_app.urlitem')),
            ],
        ),
    ]
