# Generated by Django 3.2.8 on 2021-11-02 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0006_auto_20211102_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlitem',
            name='comp_name',
        ),
        migrations.RemoveField(
            model_name='urlitem',
            name='os',
        ),
    ]
