# Generated by Django 3.2 on 2021-11-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('cohort', models.CharField(max_length=250)),
                ('favoriteTopic', models.CharField(max_length=250)),
                ('favoriteTeacher', models.CharField(max_length=250)),
                ('capstone', models.URLField()),
            ],
        ),
    ]
