# Generated by Django 3.2.9 on 2021-11-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('body', models.CharField(max_length=280)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
