# Generated by Django 3.2.8 on 2021-11-04 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
