# Generated by Django 3.2.8 on 2021-11-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photographer',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
