# Generated by Django 3.2.9 on 2021-11-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=250)),
                ('Last_Name', models.CharField(max_length=250)),
                ('Favorite_Topic', models.CharField(max_length=100)),
                ('Capstone', models.URLField(max_length=100)),
            ],
        ),
    ]
