# Generated by Django 3.2.8 on 2021-10-28 04:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery', models.TextField(max_length=50)),
                ('amount', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2021, 10, 28, 4, 5, 51, 378847, tzinfo=utc))),
            ],
        ),
    ]
