# Generated by Django 3.2.9 on 2021-11-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encoder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=30)),
                ('Date_Added', models.DateTimeField()),
                ('code', models.CharField(max_length=30)),
            ],
        ),
    ]
