# Generated by Django 3.2.9 on 2021-11-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encoder',
            name='Date_Added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
