# Generated by Django 3.2.8 on 2021-10-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0002_auto_20211028_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
