# Generated by Django 3.2.9 on 2021-11-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fav_teacher',
            new_name='favorite_teacher',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='fav_topic',
            new_name='favorite_topic',
        ),
    ]
