# Generated by Django 3.2.9 on 2021-11-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('cohort', models.CharField(max_length=200)),
                ('fav_topic', models.CharField(max_length=200)),
                ('fav_teacher', models.CharField(max_length=200)),
                ('capstone', models.URLField()),
            ],
        ),
    ]
