# Generated by Django 3.2.8 on 2021-10-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
