# Generated by Django 3.2.8 on 2021-11-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='item_text',
            field=models.CharField(max_length=20),
        ),
    ]
