# Generated by Django 3.2.9 on 2021-11-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chirp', models.CharField(max_length=140)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
