# Generated by Django 3.2.8 on 2021-11-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0003_short_user_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
