# Generated by Django 3.2.8 on 2021-11-02 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0004_short_times_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='short',
            name='user_ip',
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=50)),
                ('short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='short.short')),
            ],
        ),
    ]
