# Generated by Django 3.2.8 on 2021-11-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0005_auto_20211102_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='remote_host',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
